title = "IntelForge Gitleaks Configuration"

[extend]
useDefault = true

[allowlist]
description = "Test files and known false positives"
paths = [
    '''.*test.*''',
    '''.*mock.*''',
    '''.*fixture.*''',
    '''.*example.*''',
    '''.*demo.*''',
    '''.*sample.*''',
    '''logs/.*''',
    '''.*\.json''',
    '''.*\.md''',
    '''.*\.txt''',
    '''.*\.yaml''',
    '''.*\.yml''',
    '''.*\.toml''',
    '''.*\.cfg''',
    '''.*\.ini''',
    '''.*\.env\.example''',
    '''.*\.env\.template''',
    '''.*\.gitignore''',
    '''.*\.pre-commit-config\.yaml''',
    '''.*README\.md''',
    '''storage/.*''',
    '''development/.*''',
    '''session_docs/.*''',
    '''user created/.*''',
    '''node_modules/.*''',
    '''\..*''',
    '''snapshots/.*''',
    '''ci/.*''',
    '''docs/.*''',
    '''tools/.*''',
    '''plugins/.*''',
    '''core/.*''',
    '''chroma_storage.*''',
    '''test_data/.*''',
    '''test_snapshot.*''',
    '''release-checkpoints/.*''',
    '''\.claude/.*''',
    '''.*\.sqlite.*''',
    '''.*\.db''',
    '''.*backup.*''',
    '''.*snapshot.*''',
    '''.*export.*''',
    '''.*report.*''',
    '''.*\.html''',
    '''.*\.js''',
    '''.*\.css''',
    '''.*justfile''',
    '''.*Justfile''',
    '''venv/.*''',
    '''.*__pycache__/.*''',
    '''.*\.pyc''',
    '''.*\.pyo''',
    '''.*\.egg-info/.*''',
    '''.*\.dist-info/.*''',
    '''.*\.png''',
    '''.*\.jpg''',
    '''.*\.jpeg''',
    '''.*\.gif''',
    '''.*\.svg''',
    '''.*\.ico''',
    '''.*\.pdf''',
    '''.*\.zip''',
    '''.*\.tar\.gz''',
    '''.*\.exe''',
    '''.*\.dll''',
    '''.*\.so''',
    '''.*\.dylib''',
    '''.*\.mp3''',
    '''.*\.mp4''',
    '''.*\.avi''',
    '''.*\.mov''',
    '''.*\.wav''',
    '''.*\.ogg''',
]

stopwords = [
    'example',
    'test',
    'demo',
    'sample',
    'mock',
    'fixture',
    'template',
    'placeholder',
    'dummy',
    'fake',
    'dev',
    'development',
    'staging',
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    'INSERT_TOKEN_HERE',
    'YOUR_TOKEN_HERE',
    'CHANGE_ME',
    'REPLACE_ME',
    'TODO',
    'FIXME',
    'XXX',
    'yyy',
    'zzz',
    'aaa',
    'bbb',
    'ccc',
]
