repos:
  - repo: local
    hooks:
      - id: comprehensive-security-scan
        name: Full Security Scan
        entry: ./scripts/security_scan.sh
        language: script
        pass_filenames: false
        always_run: true